### PR TITLE
introduce gadget usage UUID

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
see phab ticket
https://phabricator.wikimedia.org/T109434

### CODE REVIEW

**Comment by thiemowmde** [comment]
Oh, please please do not do this. Wikipedia users really do not like to be tracked. What's the idea behind this? Is there a ticket? A product owner's decision? The least thing you should do is adding lots of comments to the code that explain what this is, who uses it for what and why.

**Comment by WMDE-Fisch** [comment]
We discussed the topic just now in the story time. We are very concerned about privacy matters. Unfortunately we really need some usage data. At least any way to see how many _different_ users use the gadget.

The Cirrus-Search guys even ask for it, because they want to limit the search query length[1]. We need data to convince them of the usefulness of our tool. ;-)

[1] https://phabricator.wikimedia.org/T107947

**Comment by kroll-j** [comment]
I was already starting to implement logging stuff in catgraph-jsonp for this, but on second thought...

Gathering usage data at this time is pointless. I can tell you right now that almost nobody uses it. catgraph-jsonp access.log counts 1485 accesses total since creation on June 19, which includes our testing stuff. This is not surprising since there is not even a way to enable the gadget for a typical user. Only a few people are trying it by putting code in their config.js.

=> We have no meaningful usage data because users do not even know about the gadget yet, so we should convince the Cirrus people based on the fact that users _requested_ the feature (and have done so for many years, see CatScanX and the various tools that have been created for exactly this purpose, and how popular they are).
I've posted a related comment at https://phabricator.wikimedia.org/T107947

**Comment by WMDE-Fisch** [comment]
True _atm_ the gadget is not used and we can hardly get useful usage data.

But Birgit is planing to announce the gadget big time to the end of this week. And then you never now. It could stay like it is with just 5 people using it our it could go viral and hundreds of users start trying it.

As you stated in https://phabricator.wikimedia.org/T107947 this feature was requested by many people and that's why it might get used a lot after it was announced probably. And _then_ we want to be able to look into the data and it would be _great_ to have it right away.

**Comment by kroll-j** [comment]
I'm implementing a log facility which will log the following per successful catgraph-jsonp query:
- timestamp
- graphname (i.e. wiki name)
- query string
- result length
- whether the result was truncated (only for traverse-successors, i.e. DeepCat-Gadget queries)
- GET parameters given to catgraph-jsonp

This log will show up in a publicly readable database on Labs, so you can access it and do queries on it.

If you need the number of users who installed the Gadget, see the solution by Addshore: https://phabricator.wikimedia.org/T105513#1552602 . This is the information we actually need for discussion in T107947, nothing more. This will only work when the gadget is rolled out properly, which is fine, because only then we can have a user base large enough to generate meaningful usage data. 

I object to the Gadget patch which allows tracking individual users. It is unnecessary and needlessly intrusive. People are paranoid of being tracked for a reason. I can't prevent you from merging the patch. Be aware that if you merge it, the generated data will be available to all Labs users. If it should not be publicly available you should not collect it. Please think about it.
(And I'm aware that this was not your idea, @WMDE-Fisch)

**Comment by WMDE-Fisch** [comment]
Thanks for looking into it. But please do not log the query string. We have this, very important discussion here, because we care for privacy. Logging the query string is exactly _not_ what we want and what we need. ;-)

Result length and if it was truncated is just perfect. Thanks for suggesting the latter one .

I would suggest you open a PR on the corresponding GitRepo - so we all can have a look. It is a bit to much having all that in the comments of this PR :-). And dont forget linking it in the phab ticket:

https://phabricator.wikimedia.org/T109272

**Comment by WMDE-Fisch** [comment]
About the other concerns - maybe we should continue discussing that in the phab ticket as well - see may remarks there: https://phabricator.wikimedia.org/T109434

**Comment by WMDE-Fisch** [comment]
Stalled for now, see https://phabricator.wikimedia.org/T109434

**Pull request closed without merging**
