### PR TITLE
Avoid functions beeing called before declaration

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
Introduce a main function.
Move function to declare them before usage.
Update jshint used with Travis so checks for hoisting are enabled.

Bug: T143785

### CODE REVIEW

**Comment by manicki** [comment]
As an Javascript ignorant I should probably rather stay quiet but isn't what you're doing here (moving function declarations up) actually hoisting?
If so, you're not really avoiding any hoisting here :)

**Comment by WMDE-Fisch** [comment]
You mean I should re-title it to something like "Avoid interpreter hoisting by manual hoisting."? :-D

**Comment by manicki** [comment]
dunno but assuming the interpreter does it I think you cannot **avoid** it :)

**Comment by thiemowmde** [comment]
This is really hard to review. I assume you did nothing but moving lines of code around, without touching them. If this is the case then :+1:.

**Comment by manicki** [comment]
So I spent I while on this and it looks like this is just about moving functions around and moving all the "main" code to the dedicated function. So it looks OK, and the gadget still seems to be working after the change.

I understand this is the right change to do etc. I am simply not 100% convinced by the way function are ordered now. For example `enableImeAndSuggestions` and `disableImeAndSuggestions` used to be "grouped" together, now there are 4 other functions between them. Not a biggest issue (we have IDEs etc), although this affected a readability IMO.

**Pull request merged**
