### PR TITLE
Move all CSS to the JS code

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
[Bug: T144168](http://phabricator.wikimedia.org/T144168)

### CODE REVIEW

**Comment by thiemowmde** [comment]
Huh, what? This is not nice. It's bad style actually. Why are you guys doing this?

**Comment by manicki** [comment]
I also don't really get why this is needed. To avoid having wrong styles if CSS does not get loaded when JS is loaded?

**Comment by manicki** [comment]
oh, wait, now I've seen https://phabricator.wikimedia.org/T142838#2590110
Those are valid points but still lazy loading of CSS does not equal inline styles to me.

**Comment by thiemowmde** [comment]
PerfektesChaos is a good guy, but he is not always right. Just look at the JavaScript source code he produces. This especially is just bad. Please don't do this.

**Comment by thiemowmde** [comment]
What PerfektesChaos meant is quite simple: Just move the `mw.loader.load( "…css…" );` line into the JavaScript file, so users have to copy paste only that single line and not two.

Additionally you can split the CSS into a small set that's needed before the script is fully loaded and a bigger set that's loaded later.

He also suggests that the first, small set could be inlined, but I disagree with that.

**Comment by manicki** [comment]
> What PerfektesChaos meant is quite simple: Just move the mw.loader.load( "…css…" ); line into the JavaScript file, so users have to copy paste only that single line and not two.

Indeed. I also meant this in my second comment

**Comment by WMDE-Fisch** [comment]
m( yeah your right, that would be the proper way to solve the issue. 

But I think one thing he also mentioned was, that the CSS should not necessarily load every time the script is loaded but on demand when using the tool. So I will figure something out.

**Pull request closed without merging**
