### PR TITLE
added detection for the wiki lang to compose cat graph url

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
addressing #19

### CODE REVIEW

**Comment by thiemowmde** [comment]
+2 for the code change. But I do have some questions:
- This changes `gptest1` to `de`. Is this intended?
- When the gadget is used outside of Wikipedia, e.g. on Commons, Wikidata, Wiktionary and so on, it will access an unexpected database. This was also true before, this patch does not make this worse. Just something to be aware of.
- What happens if the gadget is used in a project that's not supported by the backend service? Is there a good fallback mechanism or error message for that?

**Comment by WMDE-Fisch** [comment]
The change is necessary, so that the gadget works for most of WP.org. Since the related CirrusSearch patch is merged and deployed you can try the gadget live :-)

Dont know about the usage outside Wikipedia.

I could improve the error handling though. Atm it gives you  a "CatGraph-Tool is not reachable." when the wiki is not supported by the tool.

**Comment by kroll-j** [comment]
This does not work for Commons, Wikidata, Wiktionary etc. I'd suggest something like `location.hostname.split('.')[0]+'wiki'` instead.

**Comment by kroll-j** [comment]
After checking the [documentation](http://www.mediawiki.org/wiki/Manual:Interface/JavaScript#mw.config): 'wgDBname' is the right config variable to use. 
`mw.config.get('wgDBname')`

**Comment by kroll-j** [comment]
will test & merge this when tool labs is back up.

**Comment by thiemowmde** [comment]
+2. :-)

**Comment by WMDE-Fisch** [comment]
:+1:

**Comment by WMDE-Fisch** [comment]
@jkroll20 dont forget to delete branches after merging ;-)

**Pull request merged**
