### PR TITLE
Add JSHint configuration and run JSHint checks on TravisCI

### PR DESCRIPTION
**Pull request by wmde-manicki**

### CODE REVIEW

**Comment by wmde-manicki** [comment]
Travis build is failing due to the outdated JSCS configuration. JSCS 2.0.0 released recently is by default running checks of JSDoc blocks which has not been taken into account in `.jscsrc`.
This is about to be resolved in https://github.com/wmde/DeepCat-Gadget/pull/54, so that pull request should probably be reviewed first. I will rebase this pull request after that.

**Comment by WMDE-Fisch** [comment]
rebase :-)

**Comment by wmde-manicki** [comment]
Rebased

**Comment by WMDE-Fisch** [comment]
thx :-)

**Pull request merged**
