### PR TITLE
Additional tests

### PR DESCRIPTION
**Pull request by gbirke**
Adding some additional tests for functions that process the data from the catgraph server.

### CODE REVIEW

**Comment by thiemowmde** [comment]
More tests, yay! :-)

**Comment by WMDE-Fisch** [comment]
needs rebase :->

**Comment by thiemowmde** [comment]
Rebased.

**Comment by wmde-manicki** [comment]
Spacing is not always consistent but apart from that looks fine. I will fix this and merge once we got tests running on Travis.

**Comment by WMDE-Fisch** [comment]
needs rebase :-> @gbirke

**Comment by WMDE-Fisch** [comment]
Sorry - some of Thiemos suggestions I merged change computeResponses so that it is harder to test. I will fix that in with the next commit to this PR

**Pull request merged**
